name: Déploiement sur Azure Web App

on:
  push:
    branches:
      - principal
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: blcservice8-wq   # ⚠️ remplace par le nom exact de ton Azure Web App

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Déployer sur Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
